### Step 1
POST http://localhost:8080/create-dish/step1
Content-Type: application/json

{
  "name": "name ",
  "country": "THAILAND",
  "foodType": "GLUTEN_FREE",
  "imageUrl": "https://example.com/padthai.jpg"
}

### Step 2
POST http://localhost:8080/create-dish/step2
Content-Type: application/json

{
  "spiciness": "MILD",
  "dominantTastes": ["","SWEET","SPICY"]
}

### Step 3
POST http://localhost:8080/create-dish/step3
Content-Type: application/json

{
  "ingredients": [
    { "name": "Milk", "amount": 200, "unit": "ml" },
    { "name": "Shrimp", "amount": 150, "unit": "g" }
  ]
}

### Step 4
POST http://localhost:8080/create-dish/step4
Content-Type: application/json

{
  "description": "Soak noodles",
  "difficulty": 2,
  "videoUrl": "https://example.com/padthai.mp4"
}

